{
  "customCommands":
    [
      {
        "command": "git checkout -b {{index .PromptResponses 0}}/{{index .PromptResponses 1}}",
        "context": "localBranches",
        "description": "New branch with prefix",
        "key": "<c-n>",
        "loadingText": "Creating branch",
        "prompts":
          [
            {
              "options":
                [
                  { "name": "feature", "value": "feat" },
                  { "name": "hotfix", "value": "hotfix" },
                  { "name": "fix/bugfix", "value": "fix" },
                  { "name": "chore", "value": "chore" },
                  { "name": "experiment", "value": "experiment" },
                ],
              "title": "Creating new branch. What kind of branch is it?",
              "type": "menu",
            },
            {
              "initialValue": "",
              "title": "What is the new branch name?",
              "type": "input",
            },
          ],
      },
      {
        "command": "gh pr create --assignee @me --title \"{{.Form.title}}\" --fill \\\n{{ if ne .Form.base \"\" }}--base \"{{.Form.base}}\"{{ end }} \\\n{{.Form.draft}} \\\n{{ if eq .Form.reviewers \"other\" }}--reviewer \"{{.Form.customReviewers}}\"{{ else }}{{.Form.reviewers}}{{ end }}\n",
        "context": "files, localBranches",
        "description": "Create pull request on GitHub",
        "key": "<c-r>",
        "loadingText": "Creating pull request on GitHub",
        "prompts":
          [
            {
              "initialValue": "",
              "key": "title",
              "title": "Pull Request Title",
              "type": "input",
            },
            {
              "initialValue": "",
              "key": "base",
              "title": "Base Branch (leave empty for default branch)",
              "type": "input",
            },
            {
              "key": "draft",
              "options":
                [
                  { "name": "No", "value": "" },
                  { "name": "Yes", "value": "--draft" },
                ],
              "title": "Create as draft PR?",
              "type": "menu",
            },
            {
              "key": "reviewers",
              "options":
                [
                  {
                    "name": "CNS",
                    "value": "--reviewer peterbornerup,farhadh,benjaminbruun",
                  },
                  { "name": "None", "value": "" },
                ],
              "title": "Add Reviewers",
              "type": "menu",
            },
          ],
      },
      {
        "command": "gh repo view --web",
        "context": "localBranches",
        "description": "View Repo on GitHub",
        "key": "o",
        "loadingText": "Opening GitHub - Repository ...",
      },
      {
        "command": "gh pr view --web",
        "context": "localBranches",
        "description": "View PR on GitHub",
        "key": "O",
        "loadingText": "Opening GitHub - Pull request ...",
      },
      {
        "command": "git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{ .Form.Scope }}){{ end }}{{.Form.Breaking}}: {{.Form.Message}}'",
        "context": "global",
        "description": "Create new conventional commit",
        "key": "C",
        "loadingText": "Creating conventional commit...",
        "prompts":
          [
            {
              "key": "Type",
              "options":
                [
                  {
                    "description": "A new feature",
                    "name": "✨ feat",
                    "value": "✨ feat",
                  },
                  {
                    "description": "A bug fix",
                    "name": "☣️ fix",
                    "value": "☣️ fix",
                  },
                  {
                    "description": "Documentation only changes",
                    "name": "\U0001F4DD docs",
                    "value": "\U0001F4DD docs",
                  },
                  {
                    "description": "Non-functional formatting (e.g. spaces, semicolons)",
                    "name": "\U0001F3A8 style",
                    "value": "\U0001F3A8 style",
                  },
                  {
                    "description": "Refactor without behavior change",
                    "name": "♻️ refactor",
                    "value": "♻️ refactor",
                  },
                  {
                    "description": "Update flake and Configs",
                    "name": "\U0001F680 update",
                    "value": "\U0001F680 update",
                  },
                  {
                    "description": "Adding or correcting tests",
                    "name": "✅ test",
                    "value": "✅ test",
                  },
                  {
                    "description": "Maintenance (configs, npins, etc.)",
                    "name": "\U0001F527 chore",
                    "value": "\U0001F527 chore",
                  },
                  {
                    "description": "Build system or external dependency updates",
                    "name": "\U0001F4E6 build",
                    "value": "\U0001F4E6 build",
                  },
                  {
                    "description": "Changes to CI/CD files",
                    "name": "\U0001F916 ci",
                    "value": "\U0001F916 ci",
                  },
                  {
                    "description": "Revert a previous commit",
                    "name": "⏪ revert",
                    "value": "⏪ revert",
                  },
                ],
              "title": "Type of change",
              "type": "menu",
            },
            {
              "initialValue": "",
              "key": "Scope",
              "title": "Scope",
              "type": "input",
            },
            {
              "key": "Breaking",
              "options":
                [
                  { "name": "no", "value": "" },
                  { "name": "yes", "value": "!" },
                ],
              "title": "Breaking change",
              "type": "menu",
            },
            {
              "initialValue": "",
              "key": "Message",
              "title": "message",
              "type": "input",
            },
            {
              "body": "Are you sure you want to commit?",
              "key": "Confirm",
              "title": "Commit",
              "type": "confirm",
            },
          ],
      },
      {
        "command": "git reset --soft HEAD~1",
        "context": "files",
        "description": "Undo last commit",
        "key": "R",
      },
      {
        "command": "{{.Form.Value}}",
        "context": "global",
        "key": "a",
        "loadingText": "Pushing...",
        "prompts":
          [
            {
              "options":
                [
                  { "name": "GitHub", "value": "git push origin HEAD" },
                  { "name": "Codeberg", "value": "git push codeberg HEAD" },
                ],
              "title": "Push to:",
              "type": "menu",
            },
          ],
      },
    ],
  "disableStartupPopups": true,
  "git":
    {
      "allBranchesLogCmds":
        [
          "git log --graph --all --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'",
        ],
      "branchLogCmd": "git log --graph --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' {{branchName}} --",
      "paging":
        [
          {
            "colorArg": "always",
            "pager": 'delta --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"',
          },
        ],
      "parseEmoji": true,
    },
  "gui":
    {
      "border": "rounded",
      "branchColors":
        { "feature": "#85c87e", "hotfix": "#e06c75", "release": "#e06c75" },
      "commandLogSize": 5,
      "commitLength": { "show": true },
      "expandFocusedSidePanel": true,
      "filterMode": "fuzzy",
      "nerdFontsVersion": "3",
      "scrollHeight": 10,
      "scrollPastBottom": false,
      "showBottomLine": true,
      "showDivergenceFromBaseBranch": "arrowAndNumber",
      "showNumstatInFilesView": true,
      "showPanelJumps": false,
      "sidePanelWidth": 0.22,
      "skipRewordInEditorWarning": false,
      "statusPanelView": "allBranchesLog",
      "theme":
        {
          "activeBorderColor": ["#e06c75", "bold"],
          "cherryPickedCommitBgColor": ["#bd93f9"],
          "cherryPickedCommitFgColor": ["#82aaff"],
          "defaultFgColor": ["#cdd6f4"],
          "inactiveBorderColor": ["#61afef"],
          "markedBaseCommitBgColor": ["#e0c989"],
          "markedBaseCommitFgColor": ["#82aaff"],
          "optionsTextColor": ["#82aaff"],
          "searchingActiveBorderColor": ["#e06c75", "bold"],
          "selectedLineBgColor": ["#2a2a3a"],
          "unstagedChangesColor": ["#e06c75"],
        },
    },
  "keybinding":
    {
      "branches":
        {
          "checkoutBranchByName": "c",
          "createPullRequest": "o",
          "createTag": "T",
          "fastForward": "f",
          "fetchRemote": "f",
          "forceCheckoutBranch": "F",
          "mergeIntoCurrentBranch": "M",
          "pushTag": "P",
          "rebaseBranch": "r",
          "renameBranch": "R",
          "setUpstream": "u",
          "viewGitFlowOptions": "i",
          "viewPullRequestOptions": "O",
        },
      "commitFiles": { "checkoutCommitFile": "c" },
      "commits":
        {
          "amendToCommit": "A",
          "checkoutCommit": "<space>",
          "createFixupCommit": "F",
          "markCommitAsFixup": "f",
          "moveDownCommit": "<c-j>",
          "moveUpCommit": "<c-k>",
          "openLogMenu": "<c-l>",
          "pasteCommits": "v",
          "pickCommit": "p",
          "renameCommit": "R",
          "renameCommitWithEditor": "r",
          "resetCherryPick": "<c-R>",
          "revertCommit": "t",
          "squashAboveCommits": "S",
          "squashDown": "s",
          "tagCommit": "T",
          "viewBisectOptions": "b",
          "viewResetOptions": "g",
        },
      "files":
        {
          "amendLastCommit": "A",
          "commitChanges": "<c-c>",
          "commitChangesWithEditor": "c",
          "commitChangesWithoutHook": "w",
          "fetch": "f",
          "ignoreFile": "i",
          "openMergeOptions": "M",
          "openStatusFilter": "<c-b>",
          "refreshFiles": "r",
          "stashAllChanges": "s",
          "toggleStagedAll": "a",
          "toggleTreeView": "`",
          "viewResetOptions": "D",
          "viewStashOptions": "S",
        },
      "main": { "pickBothHunks": "b", "toggleSelectHunk": "a" },
      "stash": { "popStash": "g", "renameStash": "r" },
      "status": { "checkForUpdate": "u", "recentRepos": "<enter>" },
      "submodules": { "bulkMenu": "b", "init": "i", "update": "u" },
      "universal":
        {
          "confirm": "<enter>",
          "copyToClipboard": "<c-o>",
          "createPatchOptionsMenu": "<c-p>",
          "createRebaseOptionsMenu": "m",
          "decreaseContextInDiffView": "{",
          "diffingMenu": "W",
          "diffingMenu-alt": "<c-e>",
          "edit": "e",
          "executeShellCommand": ":",
          "extrasMenu": "@",
          "filteringMenu": "<c-s>",
          "goInto": "<enter>",
          "gotoBottom": ">",
          "gotoTop": "<",
          "increaseContextInDiffView": "}",
          "jumpToBlock": ["1", "2", "3", "4", "5"],
          "new": "n",
          "nextBlock": "<right>",
          "nextBlock-alt": "",
          "nextItem": "<down>",
          "nextItem-alt": "j",
          "nextMatch": "n",
          "nextPage": "J",
          "nextScreenMode": "+",
          "nextTab": "l",
          "openFile": "o",
          "openRecentRepos": "<c-r>",
          "optionMenu": "<disabled>",
          "optionMenu-alt1": "?",
          "prevBlock": "<left>",
          "prevBlock-alt": "",
          "prevItem": "<up>",
          "prevItem-alt": "k",
          "prevMatch": "N",
          "prevPage": "K",
          "prevScreenMode": "_",
          "prevTab": "h",
          "pullFiles": "p",
          "pushFiles": "P",
          "quit": "q",
          "quit-alt1": "<c-c>",
          "quitWithoutChangingDirectory": "Q",
          "redo": "<c-z>",
          "refresh": "R",
          "remove": "d",
          "return": "<esc>",
          "scrollDownMain": "<pgdown>",
          "scrollDownMain-alt1": "<c-d>",
          "scrollDownMain-alt2": "<disabled>",
          "scrollLeft": "H",
          "scrollRight": "L",
          "scrollUpMain": "<pgup>",
          "scrollUpMain-alt1": "<c-u>",
          "scrollUpMain-alt2": "<disabled>",
          "select": "<space>",
          "submitEditorText": "<enter>",
          "togglePanel": "<tab>",
          "toggleWhitespaceInDiffView": "<c-w>",
          "undo": "z",
        },
    },
  "notARepository": "skip",
  "os": { "editPreset": "nvim-remote" },
  "promptToReturnFromSubprocess": false,
}
